### ISSUE TITLE
Missing step in the documentation 

### ISSUE THREAD

**Issue by saasuliman** [SoftwareAG/cumulocity-demo-widget#2]
In step number 5, 

when adding the provider code : 
providers: [
{
provide: InventoryService,
useFactory: () => {
    return new InventoryService(fetchClient);
    }
}]

the library InventoryService is missing, 
so you need to clarify it should be imported using the below line: 
**import { InventoryService } from '@c8y/client';**

**Comment by DarpanLalani** [comment]
Fixed
